#!/bin/bash

LINK_DIR=/usr/local/bin
INSTALL_DIR=/opt/maxpilotto/git-tools
CONFIG=~/.gitconfig

# Aliases
read -p "Would you like to install the aliases too? (y/n) " -n 1
echo ""

if [[ $REPLY =~ [yY] ]]; then
    cat ./aliases >> $CONFIG
fi

# Main script
sudo mkdir -p $INSTALL_DIR
sudo cp -r src/. $INSTALL_DIR
sudo chmod +x $INSTALL_DIR/*
ln -sf $INSTALL_DIR/gt $LINK_DIR/gt

echo ""
echo "A symbolic link has been created @ $LINK_DIR"
echo "git-tools have been installed @ $INSTALL_DIR"
echo ""
